name: Atualizar README com Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Atualiza a cada 6 horas
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Atualizar README
        run: |
          sed -i "s|TOKEN_AQUI|${{ secrets.GH_TOKEN }}|g" README.md

      - name: Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizar README com Stats"
          git push
